### ISSUE TITLE
Changing root component with pending changes causes old root to render

### ISSUE THREAD

**Issue by ianthehenry** [swannodette/om#235]
I've made a [repo that demonstrates the bug](https://github.com/ianthehenry/om-root-bug) that will probably be more informative than my explanation.

Scenario:

- You have a root component with pending updates
- Before the next render tick, you change root components
- Expected: the pending updates are canceled
- Actual: the component with pending updates *takes over* whatever the new root is, or otherwise does something crazy

This came up in practice when I was using secretary, and for the route dispatch it was choosing the root component between a few that all shared the same `app-state`. As I'm extremely new to om, I don't know if this is the right way to do routing, but this behavior seems pretty unexpected.

**Comment by swannodette** [comment]
@bostonou thanks, fixed in master apologies for the delay
