### ISSUE TITLE
no-local preserves state across unmount/remount

### ISSUE THREAD

**Issue by brandonbloom** [swannodette/om#300]
Externalized no-local state is keyed by react-id, which is stable across unmount/remount. The unmount doesn't explicitly evict state from the global state map, so it gets preserved across an immediate unmount/remount. I'm not actually sure if this is a bug, or if it's desirable. However, it differs from the behavior without no-local, so it's worth discussing.

**Comment by jack-james** [comment]
(afaict) the new behavior goes beyond evicting a component's state from the state map, and instead just drops the entire state map.

see my comment on the commit:
https://github.com/swannodette/om/commit/dca61ad33bd8d1988f3369da653bd9e817f778f0

**Comment by swannodette** [comment]
@jack-james thanks, will fix a cut a new release

**Comment by swannodette** [comment]
Fixed in master
