### ISSUE TITLE
Support for destructuring a Map into a Cursor

### ISSUE THREAD

**Issue by rymndhng** [swannodette/om#302]
I have a very trivial app-state atom where I have a Map for which I wanted to build multiple components using `om/build-all` out of each key value pair (whose value may change). I'm a bit of a noob when trying to understand Clojure/Clojurescript Protocols and I didn't know where to start, but is there a reason why we don't/can't destructure key/value pairs into another Cursor?

p.s. I re-worked my code to use vectors as a workaround

**Comment by swannodette** [comment]
Not enough information
