### ISSUE TITLE
Consider a namespace for the project

### ISSUE THREAD

**Issue by zoowar** [swannodette/om#308]
The Om project does not have a namespace. Consider adding one (e.g. com.example/om).

**Comment by the-kenny** [comment]
Why? Given that om is usually accessed from many source files a shorter
namespace is quite fine. I strongly prefer writing om.core 20x instead
of io.github.swannodette.om.core (or whatever).

zoowar <notifications@github.com> writes:

> The Om project does not have a namespace. Consider adding one (e.g. com.example/om).
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/swannodette/om/issues/308

--

**Comment by zoowar** [comment]
I may not have been clear. Leiningen refers to "namespace" as "group-id" in the sample [project.clj](https://github.com/technomancy/leiningen/blob/stable/sample.project.clj#L11). This is an external designation, not an internal one. It affects the ":dependencis" in  users project.clj, which would be `:dependencies [[com.example/om "x.y.z"]]`, but not the ":requires" in user files. One would still write `(:requires [om.com :as om])`

**Comment by swannodette** [comment]
A group-id for the Om artifact is a good idea. Will consider it for the 0.8.0 release.

**Comment by the-kenny** [comment]
Agreed, that's totally fine. Sorry for the noise.

**Comment by swannodette** [comment]
fixed https://github.com/swannodette/om/commit/1c5e9eb1a44562be3f5936c6492dae7f624995f7

**Comment by beickhoff** [comment]
You chose a namespace that you don't own, at least not according to the usual conventions, i.e. internet domain name.

**Comment by swannodette** [comment]
@beickhoff I don't see how this possibly matters

**Comment by beickhoff** [comment]
It's just misleading.  Why use a namespace that gives the *illusion* of an internet domain name?  Just make your namespace "om", e.g.  `[om/om "x.y.z"]`

**Comment by swannodette** [comment]
@beickhoff it's just not that important. Please do not comment on this issue anymore. It will likely change in the future when Om get's some form of real web presence outside of the GitHub repo. Thanks.
