### ISSUE TITLE
Spelling mistake in basic tutorial

### ISSUE THREAD

**Issue by JulianLeviston** [swannodette/om#310]
I'm not sure if this is the appropriate place for this feedback, but please let me know what is if it's not. This is essentially a test to find out the correct place for submitting these kinds of issues are. (There are a few of them in the documentation).

In this paragraph: 

This is a lot of information. As a challenge I recommend trying to clear the text field when a real contact has been added. This is harder than it looks so don't get discouraged. If you spend more then 15, 20 minutes on it feel free to proceed to the next section and we'll show how to do it.

...more than 15 is misspelt as more then 15.

**Comment by noprompt** [comment]
@JulianLeviston The Wiki may be edited by anyone. If you see a spelling mistake or error, you are free to fix it.

**Comment by JulianLeviston** [comment]
@noprompt  awesome! thanks!
