### ISSUE TITLE
Missing Function: om.core/rendering? 

### ISSUE THREAD

**Issue by bdollard** [swannodette/om#313]
It is mentioned in the docs ( https://github.com/swannodette/om/wiki/Documentation#rendering ).
But it is not present in the code, and nothing that I saw in the changelog suggested that it has been intentionally removed.

**Comment by loganlinn** [comment]
It was removed in this commit: https://github.com/swannodette/om/commit/92a3e0cf698769fb59bb3744faddaea40b37412d

**Comment by swannodette** [comment]
Docs fixed
