### ISSUE TITLE
ReactNode & React NodeLists

### ISSUE THREAD

**Issue by JulianLeviston** [swannodette/om#314]
React has the capacity to create a function that has more than one ReactNode as its output, but Om does not seem to (apologies if this is just my lack of education). This has caused issues for me where I end up adding many divs into the output, changing the HTML structure, and causing my designer issue as his CSS needs to be adjusted.

In other words, React can produce a function whose output is `<p>hi</p><p>there</p>`. When React users use JSX, they implicitly create these NodeList objects by the form of their template. In Om, however, we explicitly create the elements we use.

An excellent explanation of React NodesLists is in a glossary under "Nodes and Elements", in https://github.com/facebook/react/blob/26636e501db170d0a8ad1cf44d61216e439df645/docs/docs/ref-09-glossary.md

Would it be possible to expose the React NodeList to Om users as a function such that we could create components that output these?

**Comment by swannodette** [comment]
Sounds interesting, will look into it.

**Comment by swannodette** [comment]
@JulianLeviston it's not clear to me what we need to do. Are people actually using React NodeList directly?

**Comment by JulianLeviston** [comment]
Apologies, I'm not sure either. I don't know much about React or Om internals. 

I'm not sure about others, but it's currently not possible in Om to have a component that outputs more than one DOM element, AFAICS. In ReactJS, from my understanding (which is probably lacking), you'd do that by using a node list, or if you were using a JSX template, ReactJS would create one for you if you had a component that outputs more than one top level DOM element.

**Comment by swannodette** [comment]
@JulianLeviston it's not clear that such a public thing exists and I'm not going to look into internals to determine how this was accomplished for JSX. Closing this until there's a way to do this through official or at least stable entry points.

**Comment by JulianLeviston** [comment]
Thanks @swannodette it actually appears that I was mistaken - it's not possible to create a react component that returns multiple tags on further investigation. Apologies for the noise. I was reading their API incorrectly. ReactNodes (and ReactFragments) are how it maintains a set of children.

What I was looking for was an empty component that doesn't render in a DOM element so I can do conditional wrappers (ie if statements that wrap multiple DOM elements), but I'll take it up with them directly rather than bother you about it. Thanks.
