### ISSUE TITLE
Alleged buggy code in the Basic Tutorial actually works fine

### ISSUE THREAD

**Issue by cobalamin** [swannodette/om#315]
In the section __Intercomponent communication__ of the basic tutorial, the following is stated:

> Evaluate the new code and try it out. As you'll see, clicking on the delete button won't do anything. In fact if you look at the JavaScript console you'll see an error about trying to manipulate a cursor outside of the render phase.
>
>What went wrong?

However, that doesn't seem to be true for me; the code works fine to delete contacts just like that, without changing to the dereferencing version (I can use `put! delete contact` fine, no need to change to `put! delete @contact`).

Did this behaviour:

>Thus you are not allowed to use cursors outside of the render phase as this is almost certainly a concurrency bug!

change in some version of Om after the tutorial was written?

**Comment by the-kenny** [comment]
cobalamin <notifications@github.com> writes:

> In the section __Intercomponent communication__ of the basic tutorial, the following is stated:
>
>> Evaluate the new code and try it out. As you'll see, clicking on the delete button won't do anything. In fact if you look at the JavaScript console you'll see an error about trying to manipulate a cursor outside of the render phase.
>>
>>What went wrong?
>
> However, that doesn't seem to be true for me; the code works fine to delete contacts just like that, without changing to the dereferencing version (I can use `put! delete contact` fine, no need to change to `put! delete @contact`).
>
> Did this behaviour:
>
>>Thus you are not allowed to use cursors outside of the render phase as this is almost certainly a concurrency bug!
>
> change in some version of Om after the tutorial was written?

Yes. See https://github.com/swannodette/om/commit/92a3e0cf698769fb59bb3744faddaea40b37412d

> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/swannodette/om/issues/315

--

**Comment by cobalamin** [comment]
Thank you, that clears it up!

Maybe the tutorial should reflect this behaviour, teaching the right version (using dereferencing) right away, including the already existing explanation?

**Comment by swannodette** [comment]
@cobalamin yes I need to go through the tutorials and update them for `0.8.0`. Or someone else could too!

**Comment by swannodette** [comment]
Closing this. Please help us keep the wiki up-to-date :)

**Comment by cobalamin** [comment]
I would gladly update the wiki if I felt like I really understood that commit and its intentions, especially compared to the previous behaviour :/

**Comment by swannodette** [comment]
@cobalamin previously there were stricter rules about deref or examining the contents of a cursor in an async context. Eventually I came to the conclusion it was all far more trouble then it was worth and not a source of real issues as I had feared in the early days.
