### ISSUE TITLE
"Official Resources" links can be better

### ISSUE THREAD

**Issue by jean** [swannodette/om#316]
The "Official Resources" links at http://swannodette.github.io/todomvc/labs/architecture-examples/om-undo/index.html all go to the front page of the blog. The linked page also states "If [...] any of the links above no longer work, please let us know.", linking to https://github.com/tastejs/todomvc/issues/ , which looks like the wrong place to file issues on this.

It looks like the links should be going to pages under https://github.com/swannodette/om/wiki

I couldn't figure out where to fix the links after a quick look.

**Comment by swannodette** [comment]
@jean this isn't a Om issue. Pull requests are welcome to the other repo. Thanks.

**Comment by jean** [comment]
OK think I figured out the right place .. https://github.com/swannodette/todomvc/pull/9
