### ISSUE TITLE
(om/get-atom owner)

### ISSUE THREAD

**Issue by olivergeorge** [swannodette/om#318]
I'm finding this hack helpful.  Perhaps there's a place for a cleaner version in the API.

```
(defn adhoc-ref [& path]
  (-> app-state (om/root-cursor) (get-in path) (om/ref-cursor)))
```

It allows me to write components which observe a ref-cursor at a path of their choosing.  

In particular, it means the component doesn't need to know about the atom but only because it's hardcoded in my helper.  That's the rub.  I think a better approach would be to complement (om/root-cursor app-state) with a new function which takes the *owner* and returns an iref to the current app-state atom.  From there things become simple.

**Comment by swannodette** [comment]
@olivergeorge not interested helper fns for this at this time. Still need collect far more information about real world ref cursor usage before we settle on extra helpers.

**Comment by JulianLeviston** [comment]
@olivergeorge prismatic's om tools might be interested FWIW
