### ISSUE TITLE
update cljsjs deps

### ISSUE THREAD

**Issue by martinklepsch** [swannodette/om#320]
We updated extern files for React 0.12.0 + above:

```clojure
[cljsjs/react "0.12.2-5"]
[cljsjs/react-with-addons "0.12.2-3"]
```

In the future I think we'll try to keep the version increments (`-5` and `-3` here) in sync so it's a little more straightforward to switch between them.

**Comment by swannodette** [comment]
fixed in master

**Comment by martinklepsch** [comment]
:+1:
