### ISSUE TITLE
Om/angular probleme routing

### ISSUE THREAD

**Issue by raphaelboukara** [swannodette/om#321]
Hello guys,
I have a simple web app with om and angular. On route www.example.com/#myroute, I reach the angular controller "mycontroller" that contain my om/root function. 
Problem: On refresh my om element is rendering on the page but when I am going to my url from link in the angular app I don't have anything from om on the screen :(
Please helpppp

**Comment by JulianLeviston** [comment]
I recommend closing this issue (as it's not a bug of Om, it's a problem you're having with using Om). Try signing up for the clojurescript mailing list and asking there (https://groups.google.com/forum/#!forum/clojurescript), or #clojurescript on IRC (freenode).

**Comment by raphaelboukara** [comment]
Ok done, i am closing
