### ISSUE TITLE
Clojars version is still 0.7.3?

### ISSUE THREAD

**Issue by tennety** [swannodette/om#323]
I was moving to using cljsjs on my project, and noticed that 0.8 versions of Om include the cljsjs react package. But the Om version on Clojars is still 0.7.3, requiring me to still include the bundled react in my cljsbuild config. What's a good way I can use om 0.8.7 with lein?

**Comment by martinklepsch** [comment]
The project has new coordinates: `org.omcljs/om`

**Comment by tennety** [comment]
Awesome, thanks @martinklepsch !!
